Added static_mac_address feature
test-kitchen/kitchen-hyperv pull request #52
Opened 2017-06-02 20:22 UTC by jdoores

Feature to add the ability to specify a static mac address in the kitchen.yml file.  I needed this due to restrictions on devices per port on our switches.  With this, I can reuse the same mac address on all my test kitchen VMs and not get one blocked due to a port violation of a "new device" on the port.

There is no testing of the input to verify it is a good mac address, because hyperv will automatically divert back to dynamic if the input isn't a valid mac address.

2017-06-05 20:33 UTC, usepowershell requested changes
Looks pretty good.. I'd just make sure the pester tests reflects the reality of how the function will be called.

![popkey](https://m.popkey.co/e28a78/5jGgy.gif)

2017-06-05 20:33 UTC, smurawski commented on spec/support/hyperv.Tests.ps1
> +        It "Should not set the StaticMacAddress for the VM" {
This test should include passing `-StaticMacAddress ""` to `New-KitchenVM` as that is what the script will do.

2017-07-04 23:25 UTC, jdoores commented
Updated pester test with suggested addition.  Ran tests and both came back green.

2017-07-05 19:39 UTC, usepowershell approved these changes

2017-07-05 19:39 UTC, merged

2017-07-05 20:39 UTC, smurawski commented
Released in v0.5.0