Fixed issue with existing stale diff disk
test-kitchen/kitchen-hyperv pull request #53
Opened 2017-06-02 21:12 UTC by jdoores

Found a bug related to having a stale differencing disk in the default location.  If a differencing disk has been made, and doesn't get destroyed for whatever reason, and then becomes out of date due to some change on the parent drive, kitchen create will fail out due to not being able to attach the drive.  

This fix adds in some conditional logic at the create differencing disk level to test if a disk is already present, and if so, tests if a VM is also present.  If so, it breaks out of the function, just as it did prior to.  However, if there is a differencing disk, and no VM present, it will delete the existing disk, then proceed to create a new one.  This logic has solved my problem of being unable to use kitchen create sometimes when an existing diff disk was already present due to it being stale from the master disk.

2017-06-05 20:20 UTC, smurawski commented
Thanks for reporting the issue and including a possible fix.. How are you getting stranded disks?  `Kitchen destroy` not cleaning up completely?  I'd rather see the fix around the destroy method to clean up existing differencing disks than guarding around create. I've been playing with adding a hook to pre-stage some files in the differencing disk and this would break that scenario.  Also, the behavior is a better fit for the destroy step.

2017-06-05 20:34 UTC, usepowershell requested changes
Thanks for reporting the issue and including a possible fix.. How are you getting stranded disks? Kitchen destroy not cleaning up completely? I'd rather see the fix around the destroy method to clean up existing differencing disks than guarding around create. I've been playing with adding a hook to pre-stage some files in the differencing disk and this would break that scenario. Also, the behavior is a better fit for the destroy step.

2017-06-07 16:56 UTC, jdoores commented
I'm not 100% sure how I ended up with a differencing disk to begin with.  I have a feeling it was due to a bad kitchen.yml which led to the creation of the disk and then the machine failed to create.  From that point, there was no machine for kitchen destroy to remove, which led to a disk being left on the file system.  That's all speculation though.  I'll modify my code to check for a disk during the destroy process instead, regardless if a machine is found.

2017-07-03 18:36 UTC, jdoores commented
I made the changes requested, moving the check to kitchen destroy from kitchen create.  

I also think the reason I ended up with a differencing disk to begin with was due to my termination of the kitchen create batch process before it finished.  I was messing with connection info (username/password) and it was taking several minutes to time out.  Much quicker to just cancel and recreate, but I think that left me with a disk and no VM to destroy.  Then after modifying the base machine the existing diff disk was stale and kitchen create would error out due to an existing disk.  The changes made should resolve that.

2017-07-03 18:49 UTC, mwrock approved these changes

2017-07-05 19:36 UTC, usepowershell approved these changes

2017-07-05 19:36 UTC, merged

2017-07-05 20:39 UTC, usepowershell commented
Released in v0.5.0