Get parent VM generation if none are specified in kitchen.yml
test-kitchen/kitchen-hyperv pull request #61
Opened 2017-12-22 00:40 UTC by jdoores

This code will do the work of getting the parent VM generation for creating the new machine, if one is not specified in the kitchen.yml.  This works in the case of both no checkpoints, or checkpoints on the parent VM.  

It also respects the generation specified in the kitchen.yml if there is one.  This way, if someone accidentally forgets that line and is running a generation 2 machine, the machine wont create and inexplicably not boot without any good information.

2018-01-03 01:51 UTC, usepowershell requested changes
Great stuff. We just need to handle the case where the parent vhd is not associated to a vm.

2018-01-03 02:24 UTC, kdoores commented
The function will raise an error when no generation is returned (such as if the vhdx isn't attached to a VM).  Would you prefer it to set a value instead?  Or would you prefer me to make the error more descriptive?

2018-01-03 21:48 UTC, kdoores commented
Scratch that last comment, after testing here I see it the machine can create without the vhdx attached to a machine. I'll default it to a gen 1 machine at that point, and write a note to the console.  Changes should be incoming soon.

2018-01-06 01:55 UTC, kdoores commented
Requested changes implemented.

2023-08-23 13:23 UTC, closed without merging